export const ROLES = ["MEMBER", "MODERATOR", "ADMIN", "SUPER_ADMIN"] as const;

export type AppRole = (typeof ROLES)[number];

export const ADMIN_PERMISSIONS = [
  "ADMIN_ACCESS",
  "ADMIN_VIEW_PLATFORM_OVERVIEW",
  "REPORT_LIST",
  "REPORT_VIEW",
  "REPORT_CLAIM",
  "REPORT_ADD_NOTE",
  "REPORT_TRANSITION_ASSIGNED",
  "REPORT_VIEW_EVIDENCE_REDACTED",
  "REPORT_ASSIGN_ANY",
  "REPORT_REOPEN",
  "REPORT_VIEW_EVIDENCE_FULL",
  "AUDIT_VIEW_CASE",
  "AUDIT_VIEW_GLOBAL",
  "AUDIT_VIEW_SECURITY_METADATA",
  "REFERENCE_DATA_VIEW",
  "REFERENCE_DATA_MANAGE",
  "MEDIA_VIEW",
  "MEDIA_MANAGE",
  "USER_VIEW",
  "USER_MANAGE",
  "USER_ROLE_MANAGE",
  "ACCOUNT_REQUEST_MANAGE",
  "NOTIFICATION_VIEW",
  "NOTIFICATION_MANAGE",
  "MESSAGE_SAFETY_VIEW",
  "COMMUNITY_CMS_VIEW",
  "COMMUNITY_CMS_MANAGE",
  "MARKETPLACE_CMS_VIEW",
  "MARKETPLACE_CMS_MANAGE",
  "HOUSING_VIEW",
  "HOUSING_MODERATE",
  "HOUSING_LISTINGS_REVIEW",
  "HOUSING_LISTINGS_REMOVE",
  "HOUSING_REQUESTS_MODERATE",
  "ROOMMATE_PROFILES_MODERATE",
  "HOUSING_PROOF_VIEW",
  "HOUSING_PUBLISHERS_RESTRICT",
  "GUIDE_CMS_VIEW",
  "GUIDE_CMS_MANAGE",
  "CITY_CMS_VIEW",
  "CITY_CMS_MANAGE",
  "STORY_CMS_VIEW",
  "STORY_CMS_MANAGE",
  "OFFICIAL_PROFILE_VIEW",
  "OFFICIAL_PROFILE_MANAGE",
  "ORGANIZATIONS_VIEW",
  "ORGANIZATIONS_MANAGE",
  "ORGANIZATIONS_SUSPEND",
  "ORGANIZATIONS_ARCHIVE",
  "ORGANIZATION_VERIFICATIONS_VIEW",
  "ORGANIZATION_VERIFICATIONS_REVIEW",
  "ORGANIZATION_PARTNER_STATUS_MANAGE",
  "ORGANIZATION_PUBLIC_PROFILES_VIEW",
  "ORGANIZATION_PUBLIC_PROFILES_MODERATE",
  "ORGANIZATION_PUBLIC_PROFILES_UNPUBLISH",
  "ORGANIZATION_PUBLIC_PROFILES_RESTORE",
  "FEEDBACK_VIEW",
  "FEEDBACK_MANAGE",
  "STUDENT_HUB_CONFIG_VIEW",
  "STUDENT_HUB_CONFIG_MANAGE",
  "OPPORTUNITIES_VIEW",
  "OPPORTUNITIES_MANAGE",
  "OPPORTUNITIES_REVIEW",
  "OPPORTUNITIES_REMOVE",
  // Platform access to applicant data is narrow and purpose-limited. It is not
  // granted to MODERATOR and is never implied by OPPORTUNITIES_MANAGE.
  "OPPORTUNITY_APPLICATIONS_VIEW",
  "OPPORTUNITY_APPLICATIONS_SUPPORT",
  "OPPORTUNITY_REPORTS_REVIEW",
  "SCHOLARSHIP_AGENTS_VIEW",
  "SCHOLARSHIP_AGENTS_MANAGE",
  "OPPORTUNITY_PUBLISHERS_RESTRICT",
  "ANALYTICS_VIEW",
  "PLATFORM_SETTINGS_VIEW",
  "PLATFORM_SETTINGS_MANAGE",
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];

const ROLE_PERMISSIONS: Record<AppRole, readonly AdminPermission[]> = {
  MEMBER: [],
  MODERATOR: [
    "ADMIN_ACCESS",
    "REPORT_LIST",
    "REPORT_VIEW",
    "REPORT_CLAIM",
    "REPORT_ADD_NOTE",
    "REPORT_TRANSITION_ASSIGNED",
    "REPORT_VIEW_EVIDENCE_REDACTED",
    "AUDIT_VIEW_CASE",
    "STORY_CMS_VIEW",
    "STORY_CMS_MANAGE",
    "HOUSING_VIEW",
    "HOUSING_LISTINGS_REVIEW",
    "OPPORTUNITIES_VIEW",
    "OPPORTUNITIES_REVIEW",
    "OPPORTUNITY_REPORTS_REVIEW",
  ],
  ADMIN: [
    "ADMIN_ACCESS",
    "ADMIN_VIEW_PLATFORM_OVERVIEW",
    "REPORT_LIST",
    "REPORT_VIEW",
    "REPORT_CLAIM",
    "REPORT_ADD_NOTE",
    "REPORT_TRANSITION_ASSIGNED",
    "REPORT_VIEW_EVIDENCE_REDACTED",
    "REPORT_ASSIGN_ANY",
    "REPORT_REOPEN",
    "REPORT_VIEW_EVIDENCE_FULL",
    "AUDIT_VIEW_CASE",
    "AUDIT_VIEW_GLOBAL",
    "REFERENCE_DATA_VIEW",
    "REFERENCE_DATA_MANAGE",
    "MEDIA_VIEW",
    "MEDIA_MANAGE",
    "USER_VIEW",
    "USER_MANAGE",
    "ACCOUNT_REQUEST_MANAGE",
    "NOTIFICATION_VIEW",
    "NOTIFICATION_MANAGE",
    "MESSAGE_SAFETY_VIEW",
    "COMMUNITY_CMS_VIEW",
    "COMMUNITY_CMS_MANAGE",
    "MARKETPLACE_CMS_VIEW",
    "MARKETPLACE_CMS_MANAGE",
    "HOUSING_VIEW",
    "HOUSING_MODERATE",
    "HOUSING_LISTINGS_REVIEW",
    "HOUSING_LISTINGS_REMOVE",
    "HOUSING_REQUESTS_MODERATE",
    "ROOMMATE_PROFILES_MODERATE",
    "HOUSING_PROOF_VIEW",
    "GUIDE_CMS_VIEW",
    "GUIDE_CMS_MANAGE",
    "CITY_CMS_VIEW",
    "CITY_CMS_MANAGE",
    "STORY_CMS_VIEW",
    "STORY_CMS_MANAGE",
    "OFFICIAL_PROFILE_VIEW",
    "OFFICIAL_PROFILE_MANAGE",
    "ORGANIZATIONS_VIEW",
    "ORGANIZATIONS_MANAGE",
    "ORGANIZATIONS_SUSPEND",
    "ORGANIZATIONS_ARCHIVE",
    "ORGANIZATION_VERIFICATIONS_VIEW",
    "ORGANIZATION_VERIFICATIONS_REVIEW",
    "ORGANIZATION_PUBLIC_PROFILES_VIEW",
    "ORGANIZATION_PUBLIC_PROFILES_MODERATE",
    "ORGANIZATION_PUBLIC_PROFILES_UNPUBLISH",
    "ORGANIZATION_PUBLIC_PROFILES_RESTORE",
    "FEEDBACK_VIEW",
    "FEEDBACK_MANAGE",
    "STUDENT_HUB_CONFIG_VIEW",
    "STUDENT_HUB_CONFIG_MANAGE",
    "OPPORTUNITIES_VIEW",
    "OPPORTUNITIES_MANAGE",
    "OPPORTUNITIES_REVIEW",
    "OPPORTUNITIES_REMOVE",
    "OPPORTUNITY_REPORTS_REVIEW",
    "SCHOLARSHIP_AGENTS_VIEW",
    "SCHOLARSHIP_AGENTS_MANAGE",
    "OPPORTUNITY_PUBLISHERS_RESTRICT",
    "ANALYTICS_VIEW",
    "PLATFORM_SETTINGS_VIEW",
    "PLATFORM_SETTINGS_MANAGE",
  ],
  SUPER_ADMIN: ADMIN_PERMISSIONS,
};

export function isAdminRole(role: AppRole | string | null | undefined) {
  return role === "ADMIN" || role === "SUPER_ADMIN";
}

export function isModeratorRole(role: AppRole | string | null | undefined) {
  return role === "MODERATOR" || isAdminRole(role);
}

export function isSuperAdminRole(role: AppRole | string | null | undefined) {
  return role === "SUPER_ADMIN";
}

export function hasRole(
  role: AppRole | string | null | undefined,
  allowedRoles: readonly AppRole[],
) {
  return Boolean(role && allowedRoles.includes(role as AppRole));
}

export function canAccessAdmin(role: AppRole | string | null | undefined) {
  return hasAdminPermission(role, "ADMIN_ACCESS");
}

export function canManageResource(args: {
  role: AppRole | string | null | undefined;
  userId: string;
  ownerId: string;
}) {
  return isModeratorRole(args.role) || args.userId === args.ownerId;
}

export function permissionsForRole(
  role: AppRole | string | null | undefined,
): readonly AdminPermission[] {
  if (!role || !ROLES.includes(role as AppRole)) return [];
  return ROLE_PERMISSIONS[role as AppRole];
}

export function hasAdminPermission(
  role: AppRole | string | null | undefined,
  permission: AdminPermission,
) {
  return permissionsForRole(role).includes(permission);
}
