/**
 * Every ISO 3166-1 country and territory Kondo accepts, sorted by English
 * name. Kondo is a digital ecosystem for international students in China, so
 * the country dimension has to cover the whole world: a student from Pakistan,
 * Kazakhstan, France or Cameroon all reach Kondo through the same selector.
 *
 * Names come from the CLDR English region names, flags from the ISO code
 * itself. Regenerate with `npm run reference:countries`.
 */
export type CountryRegion =
  | "Africa"
  | "Americas"
  | "Asia"
  | "Europe"
  | "Oceania";

export type CountryReference = {
  code: string;
  name: string;
  emoji: string;
  region: CountryRegion;
};

export const COUNTRIES: readonly CountryReference[] = [
  { code: "AF", name: "Afghanistan", emoji: "🇦🇫", region: "Asia" },
  { code: "AX", name: "Åland Islands", emoji: "🇦🇽", region: "Europe" },
  { code: "AL", name: "Albania", emoji: "🇦🇱", region: "Europe" },
  { code: "DZ", name: "Algeria", emoji: "🇩🇿", region: "Africa" },
  { code: "AS", name: "American Samoa", emoji: "🇦🇸", region: "Oceania" },
  { code: "AD", name: "Andorra", emoji: "🇦🇩", region: "Europe" },
  { code: "AO", name: "Angola", emoji: "🇦🇴", region: "Africa" },
  { code: "AI", name: "Anguilla", emoji: "🇦🇮", region: "Americas" },
  { code: "AG", name: "Antigua and Barbuda", emoji: "🇦🇬", region: "Americas" },
  { code: "AR", name: "Argentina", emoji: "🇦🇷", region: "Americas" },
  { code: "AM", name: "Armenia", emoji: "🇦🇲", region: "Asia" },
  { code: "AW", name: "Aruba", emoji: "🇦🇼", region: "Americas" },
  { code: "AU", name: "Australia", emoji: "🇦🇺", region: "Oceania" },
  { code: "AT", name: "Austria", emoji: "🇦🇹", region: "Europe" },
  { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿", region: "Asia" },
  { code: "BS", name: "Bahamas", emoji: "🇧🇸", region: "Americas" },
  { code: "BH", name: "Bahrain", emoji: "🇧🇭", region: "Asia" },
  { code: "BD", name: "Bangladesh", emoji: "🇧🇩", region: "Asia" },
  { code: "BB", name: "Barbados", emoji: "🇧🇧", region: "Americas" },
  { code: "BY", name: "Belarus", emoji: "🇧🇾", region: "Europe" },
  { code: "BE", name: "Belgium", emoji: "🇧🇪", region: "Europe" },
  { code: "BZ", name: "Belize", emoji: "🇧🇿", region: "Americas" },
  { code: "BJ", name: "Benin", emoji: "🇧🇯", region: "Africa" },
  { code: "BM", name: "Bermuda", emoji: "🇧🇲", region: "Americas" },
  { code: "BT", name: "Bhutan", emoji: "🇧🇹", region: "Asia" },
  { code: "BO", name: "Bolivia", emoji: "🇧🇴", region: "Americas" },
  { code: "BA", name: "Bosnia and Herzegovina", emoji: "🇧🇦", region: "Europe" },
  { code: "BW", name: "Botswana", emoji: "🇧🇼", region: "Africa" },
  { code: "BR", name: "Brazil", emoji: "🇧🇷", region: "Americas" },
  {
    code: "VG",
    name: "British Virgin Islands",
    emoji: "🇻🇬",
    region: "Americas",
  },
  { code: "BN", name: "Brunei", emoji: "🇧🇳", region: "Asia" },
  { code: "BG", name: "Bulgaria", emoji: "🇧🇬", region: "Europe" },
  { code: "BF", name: "Burkina Faso", emoji: "🇧🇫", region: "Africa" },
  { code: "BI", name: "Burundi", emoji: "🇧🇮", region: "Africa" },
  { code: "CV", name: "Cabo Verde", emoji: "🇨🇻", region: "Africa" },
  { code: "KH", name: "Cambodia", emoji: "🇰🇭", region: "Asia" },
  { code: "CM", name: "Cameroon", emoji: "🇨🇲", region: "Africa" },
  { code: "CA", name: "Canada", emoji: "🇨🇦", region: "Americas" },
  {
    code: "BQ",
    name: "Caribbean Netherlands",
    emoji: "🇧🇶",
    region: "Americas",
  },
  { code: "KY", name: "Cayman Islands", emoji: "🇰🇾", region: "Americas" },
  {
    code: "CF",
    name: "Central African Republic",
    emoji: "🇨🇫",
    region: "Africa",
  },
  { code: "TD", name: "Chad", emoji: "🇹🇩", region: "Africa" },
  { code: "CL", name: "Chile", emoji: "🇨🇱", region: "Americas" },
  { code: "CN", name: "China", emoji: "🇨🇳", region: "Asia" },
  { code: "CO", name: "Colombia", emoji: "🇨🇴", region: "Americas" },
  { code: "KM", name: "Comoros", emoji: "🇰🇲", region: "Africa" },
  { code: "CK", name: "Cook Islands", emoji: "🇨🇰", region: "Oceania" },
  { code: "CR", name: "Costa Rica", emoji: "🇨🇷", region: "Americas" },
  { code: "CI", name: "Côte d’Ivoire", emoji: "🇨🇮", region: "Africa" },
  { code: "HR", name: "Croatia", emoji: "🇭🇷", region: "Europe" },
  { code: "CU", name: "Cuba", emoji: "🇨🇺", region: "Americas" },
  { code: "CW", name: "Curaçao", emoji: "🇨🇼", region: "Americas" },
  { code: "CY", name: "Cyprus", emoji: "🇨🇾", region: "Asia" },
  { code: "CZ", name: "Czechia", emoji: "🇨🇿", region: "Europe" },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    emoji: "🇨🇩",
    region: "Africa",
  },
  { code: "DK", name: "Denmark", emoji: "🇩🇰", region: "Europe" },
  { code: "DJ", name: "Djibouti", emoji: "🇩🇯", region: "Africa" },
  { code: "DM", name: "Dominica", emoji: "🇩🇲", region: "Americas" },
  { code: "DO", name: "Dominican Republic", emoji: "🇩🇴", region: "Americas" },
  { code: "EC", name: "Ecuador", emoji: "🇪🇨", region: "Americas" },
  { code: "EG", name: "Egypt", emoji: "🇪🇬", region: "Africa" },
  { code: "SV", name: "El Salvador", emoji: "🇸🇻", region: "Americas" },
  { code: "GQ", name: "Equatorial Guinea", emoji: "🇬🇶", region: "Africa" },
  { code: "ER", name: "Eritrea", emoji: "🇪🇷", region: "Africa" },
  { code: "EE", name: "Estonia", emoji: "🇪🇪", region: "Europe" },
  { code: "SZ", name: "Eswatini", emoji: "🇸🇿", region: "Africa" },
  { code: "ET", name: "Ethiopia", emoji: "🇪🇹", region: "Africa" },
  { code: "FK", name: "Falkland Islands", emoji: "🇫🇰", region: "Americas" },
  { code: "FO", name: "Faroe Islands", emoji: "🇫🇴", region: "Europe" },
  { code: "FJ", name: "Fiji", emoji: "🇫🇯", region: "Oceania" },
  { code: "FI", name: "Finland", emoji: "🇫🇮", region: "Europe" },
  { code: "FR", name: "France", emoji: "🇫🇷", region: "Europe" },
  { code: "GF", name: "French Guiana", emoji: "🇬🇫", region: "Americas" },
  { code: "PF", name: "French Polynesia", emoji: "🇵🇫", region: "Oceania" },
  { code: "GA", name: "Gabon", emoji: "🇬🇦", region: "Africa" },
  { code: "GM", name: "Gambia", emoji: "🇬🇲", region: "Africa" },
  { code: "GE", name: "Georgia", emoji: "🇬🇪", region: "Asia" },
  { code: "DE", name: "Germany", emoji: "🇩🇪", region: "Europe" },
  { code: "GH", name: "Ghana", emoji: "🇬🇭", region: "Africa" },
  { code: "GI", name: "Gibraltar", emoji: "🇬🇮", region: "Europe" },
  { code: "GR", name: "Greece", emoji: "🇬🇷", region: "Europe" },
  { code: "GL", name: "Greenland", emoji: "🇬🇱", region: "Americas" },
  { code: "GD", name: "Grenada", emoji: "🇬🇩", region: "Americas" },
  { code: "GP", name: "Guadeloupe", emoji: "🇬🇵", region: "Americas" },
  { code: "GU", name: "Guam", emoji: "🇬🇺", region: "Oceania" },
  { code: "GT", name: "Guatemala", emoji: "🇬🇹", region: "Americas" },
  { code: "GG", name: "Guernsey", emoji: "🇬🇬", region: "Europe" },
  { code: "GN", name: "Guinea", emoji: "🇬🇳", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", emoji: "🇬🇼", region: "Africa" },
  { code: "GY", name: "Guyana", emoji: "🇬🇾", region: "Americas" },
  { code: "HT", name: "Haiti", emoji: "🇭🇹", region: "Americas" },
  { code: "HN", name: "Honduras", emoji: "🇭🇳", region: "Americas" },
  { code: "HK", name: "Hong Kong", emoji: "🇭🇰", region: "Asia" },
  { code: "HU", name: "Hungary", emoji: "🇭🇺", region: "Europe" },
  { code: "IS", name: "Iceland", emoji: "🇮🇸", region: "Europe" },
  { code: "IN", name: "India", emoji: "🇮🇳", region: "Asia" },
  { code: "ID", name: "Indonesia", emoji: "🇮🇩", region: "Asia" },
  { code: "IR", name: "Iran", emoji: "🇮🇷", region: "Asia" },
  { code: "IQ", name: "Iraq", emoji: "🇮🇶", region: "Asia" },
  { code: "IE", name: "Ireland", emoji: "🇮🇪", region: "Europe" },
  { code: "IM", name: "Isle of Man", emoji: "🇮🇲", region: "Europe" },
  { code: "IL", name: "Israel", emoji: "🇮🇱", region: "Asia" },
  { code: "IT", name: "Italy", emoji: "🇮🇹", region: "Europe" },
  { code: "JM", name: "Jamaica", emoji: "🇯🇲", region: "Americas" },
  { code: "JP", name: "Japan", emoji: "🇯🇵", region: "Asia" },
  { code: "JE", name: "Jersey", emoji: "🇯🇪", region: "Europe" },
  { code: "JO", name: "Jordan", emoji: "🇯🇴", region: "Asia" },
  { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿", region: "Asia" },
  { code: "KE", name: "Kenya", emoji: "🇰🇪", region: "Africa" },
  { code: "KI", name: "Kiribati", emoji: "🇰🇮", region: "Oceania" },
  { code: "XK", name: "Kosovo", emoji: "🇽🇰", region: "Europe" },
  { code: "KW", name: "Kuwait", emoji: "🇰🇼", region: "Asia" },
  { code: "KG", name: "Kyrgyzstan", emoji: "🇰🇬", region: "Asia" },
  { code: "LA", name: "Laos", emoji: "🇱🇦", region: "Asia" },
  { code: "LV", name: "Latvia", emoji: "🇱🇻", region: "Europe" },
  { code: "LB", name: "Lebanon", emoji: "🇱🇧", region: "Asia" },
  { code: "LS", name: "Lesotho", emoji: "🇱🇸", region: "Africa" },
  { code: "LR", name: "Liberia", emoji: "🇱🇷", region: "Africa" },
  { code: "LY", name: "Libya", emoji: "🇱🇾", region: "Africa" },
  { code: "LI", name: "Liechtenstein", emoji: "🇱🇮", region: "Europe" },
  { code: "LT", name: "Lithuania", emoji: "🇱🇹", region: "Europe" },
  { code: "LU", name: "Luxembourg", emoji: "🇱🇺", region: "Europe" },
  { code: "MO", name: "Macao", emoji: "🇲🇴", region: "Asia" },
  { code: "MG", name: "Madagascar", emoji: "🇲🇬", region: "Africa" },
  { code: "MW", name: "Malawi", emoji: "🇲🇼", region: "Africa" },
  { code: "MY", name: "Malaysia", emoji: "🇲🇾", region: "Asia" },
  { code: "MV", name: "Maldives", emoji: "🇲🇻", region: "Asia" },
  { code: "ML", name: "Mali", emoji: "🇲🇱", region: "Africa" },
  { code: "MT", name: "Malta", emoji: "🇲🇹", region: "Europe" },
  { code: "MH", name: "Marshall Islands", emoji: "🇲🇭", region: "Oceania" },
  { code: "MQ", name: "Martinique", emoji: "🇲🇶", region: "Americas" },
  { code: "MR", name: "Mauritania", emoji: "🇲🇷", region: "Africa" },
  { code: "MU", name: "Mauritius", emoji: "🇲🇺", region: "Africa" },
  { code: "YT", name: "Mayotte", emoji: "🇾🇹", region: "Africa" },
  { code: "MX", name: "Mexico", emoji: "🇲🇽", region: "Americas" },
  { code: "FM", name: "Micronesia", emoji: "🇫🇲", region: "Oceania" },
  { code: "MD", name: "Moldova", emoji: "🇲🇩", region: "Europe" },
  { code: "MC", name: "Monaco", emoji: "🇲🇨", region: "Europe" },
  { code: "MN", name: "Mongolia", emoji: "🇲🇳", region: "Asia" },
  { code: "ME", name: "Montenegro", emoji: "🇲🇪", region: "Europe" },
  { code: "MS", name: "Montserrat", emoji: "🇲🇸", region: "Americas" },
  { code: "MA", name: "Morocco", emoji: "🇲🇦", region: "Africa" },
  { code: "MZ", name: "Mozambique", emoji: "🇲🇿", region: "Africa" },
  { code: "MM", name: "Myanmar (Burma)", emoji: "🇲🇲", region: "Asia" },
  { code: "NA", name: "Namibia", emoji: "🇳🇦", region: "Africa" },
  { code: "NR", name: "Nauru", emoji: "🇳🇷", region: "Oceania" },
  { code: "NP", name: "Nepal", emoji: "🇳🇵", region: "Asia" },
  { code: "NL", name: "Netherlands", emoji: "🇳🇱", region: "Europe" },
  { code: "NC", name: "New Caledonia", emoji: "🇳🇨", region: "Oceania" },
  { code: "NZ", name: "New Zealand", emoji: "🇳🇿", region: "Oceania" },
  { code: "NI", name: "Nicaragua", emoji: "🇳🇮", region: "Americas" },
  { code: "NE", name: "Niger", emoji: "🇳🇪", region: "Africa" },
  { code: "NG", name: "Nigeria", emoji: "🇳🇬", region: "Africa" },
  { code: "NU", name: "Niue", emoji: "🇳🇺", region: "Oceania" },
  { code: "NF", name: "Norfolk Island", emoji: "🇳🇫", region: "Oceania" },
  { code: "KP", name: "North Korea", emoji: "🇰🇵", region: "Asia" },
  { code: "MK", name: "North Macedonia", emoji: "🇲🇰", region: "Europe" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
    region: "Oceania",
  },
  { code: "NO", name: "Norway", emoji: "🇳🇴", region: "Europe" },
  { code: "OM", name: "Oman", emoji: "🇴🇲", region: "Asia" },
  { code: "PK", name: "Pakistan", emoji: "🇵🇰", region: "Asia" },
  { code: "PW", name: "Palau", emoji: "🇵🇼", region: "Oceania" },
  { code: "PS", name: "Palestine", emoji: "🇵🇸", region: "Asia" },
  { code: "PA", name: "Panama", emoji: "🇵🇦", region: "Americas" },
  { code: "PG", name: "Papua New Guinea", emoji: "🇵🇬", region: "Oceania" },
  { code: "PY", name: "Paraguay", emoji: "🇵🇾", region: "Americas" },
  { code: "PE", name: "Peru", emoji: "🇵🇪", region: "Americas" },
  { code: "PH", name: "Philippines", emoji: "🇵🇭", region: "Asia" },
  { code: "PN", name: "Pitcairn Islands", emoji: "🇵🇳", region: "Oceania" },
  { code: "PL", name: "Poland", emoji: "🇵🇱", region: "Europe" },
  { code: "PT", name: "Portugal", emoji: "🇵🇹", region: "Europe" },
  { code: "PR", name: "Puerto Rico", emoji: "🇵🇷", region: "Americas" },
  { code: "QA", name: "Qatar", emoji: "🇶🇦", region: "Asia" },
  { code: "CG", name: "Republic of the Congo", emoji: "🇨🇬", region: "Africa" },
  { code: "RE", name: "Réunion", emoji: "🇷🇪", region: "Africa" },
  { code: "RO", name: "Romania", emoji: "🇷🇴", region: "Europe" },
  { code: "RU", name: "Russia", emoji: "🇷🇺", region: "Europe" },
  { code: "RW", name: "Rwanda", emoji: "🇷🇼", region: "Africa" },
  { code: "WS", name: "Samoa", emoji: "🇼🇸", region: "Oceania" },
  { code: "SM", name: "San Marino", emoji: "🇸🇲", region: "Europe" },
  { code: "ST", name: "São Tomé and Príncipe", emoji: "🇸🇹", region: "Africa" },
  { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦", region: "Asia" },
  { code: "SN", name: "Senegal", emoji: "🇸🇳", region: "Africa" },
  { code: "RS", name: "Serbia", emoji: "🇷🇸", region: "Europe" },
  { code: "SC", name: "Seychelles", emoji: "🇸🇨", region: "Africa" },
  { code: "SL", name: "Sierra Leone", emoji: "🇸🇱", region: "Africa" },
  { code: "SG", name: "Singapore", emoji: "🇸🇬", region: "Asia" },
  { code: "SX", name: "Sint Maarten", emoji: "🇸🇽", region: "Americas" },
  { code: "SK", name: "Slovakia", emoji: "🇸🇰", region: "Europe" },
  { code: "SI", name: "Slovenia", emoji: "🇸🇮", region: "Europe" },
  { code: "SB", name: "Solomon Islands", emoji: "🇸🇧", region: "Oceania" },
  { code: "SO", name: "Somalia", emoji: "🇸🇴", region: "Africa" },
  { code: "ZA", name: "South Africa", emoji: "🇿🇦", region: "Africa" },
  { code: "KR", name: "South Korea", emoji: "🇰🇷", region: "Asia" },
  { code: "SS", name: "South Sudan", emoji: "🇸🇸", region: "Africa" },
  { code: "ES", name: "Spain", emoji: "🇪🇸", region: "Europe" },
  { code: "LK", name: "Sri Lanka", emoji: "🇱🇰", region: "Asia" },
  { code: "BL", name: "St. Barthélemy", emoji: "🇧🇱", region: "Americas" },
  { code: "SH", name: "St. Helena", emoji: "🇸🇭", region: "Africa" },
  { code: "KN", name: "St. Kitts and Nevis", emoji: "🇰🇳", region: "Americas" },
  { code: "LC", name: "St. Lucia", emoji: "🇱🇨", region: "Americas" },
  { code: "MF", name: "St. Martin", emoji: "🇲🇫", region: "Americas" },
  {
    code: "PM",
    name: "St. Pierre and Miquelon",
    emoji: "🇵🇲",
    region: "Americas",
  },
  {
    code: "VC",
    name: "St. Vincent and Grenadines",
    emoji: "🇻🇨",
    region: "Americas",
  },
  { code: "SD", name: "Sudan", emoji: "🇸🇩", region: "Africa" },
  { code: "SR", name: "Suriname", emoji: "🇸🇷", region: "Americas" },
  { code: "SJ", name: "Svalbard and Jan Mayen", emoji: "🇸🇯", region: "Europe" },
  { code: "SE", name: "Sweden", emoji: "🇸🇪", region: "Europe" },
  { code: "CH", name: "Switzerland", emoji: "🇨🇭", region: "Europe" },
  { code: "SY", name: "Syria", emoji: "🇸🇾", region: "Asia" },
  { code: "TW", name: "Taiwan", emoji: "🇹🇼", region: "Asia" },
  { code: "TJ", name: "Tajikistan", emoji: "🇹🇯", region: "Asia" },
  { code: "TZ", name: "Tanzania", emoji: "🇹🇿", region: "Africa" },
  { code: "TH", name: "Thailand", emoji: "🇹🇭", region: "Asia" },
  { code: "TL", name: "Timor-Leste", emoji: "🇹🇱", region: "Asia" },
  { code: "TG", name: "Togo", emoji: "🇹🇬", region: "Africa" },
  { code: "TK", name: "Tokelau", emoji: "🇹🇰", region: "Oceania" },
  { code: "TO", name: "Tonga", emoji: "🇹🇴", region: "Oceania" },
  { code: "TT", name: "Trinidad and Tobago", emoji: "🇹🇹", region: "Americas" },
  { code: "TN", name: "Tunisia", emoji: "🇹🇳", region: "Africa" },
  { code: "TR", name: "Türkiye", emoji: "🇹🇷", region: "Asia" },
  { code: "TM", name: "Turkmenistan", emoji: "🇹🇲", region: "Asia" },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    emoji: "🇹🇨",
    region: "Americas",
  },
  { code: "TV", name: "Tuvalu", emoji: "🇹🇻", region: "Oceania" },
  { code: "UM", name: "U.S. Outlying Islands", emoji: "🇺🇲", region: "Oceania" },
  { code: "VI", name: "U.S. Virgin Islands", emoji: "🇻🇮", region: "Americas" },
  { code: "UG", name: "Uganda", emoji: "🇺🇬", region: "Africa" },
  { code: "UA", name: "Ukraine", emoji: "🇺🇦", region: "Europe" },
  { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪", region: "Asia" },
  { code: "GB", name: "United Kingdom", emoji: "🇬🇧", region: "Europe" },
  { code: "US", name: "United States", emoji: "🇺🇸", region: "Americas" },
  { code: "UY", name: "Uruguay", emoji: "🇺🇾", region: "Americas" },
  { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿", region: "Asia" },
  { code: "VU", name: "Vanuatu", emoji: "🇻🇺", region: "Oceania" },
  { code: "VA", name: "Vatican City", emoji: "🇻🇦", region: "Europe" },
  { code: "VE", name: "Venezuela", emoji: "🇻🇪", region: "Americas" },
  { code: "VN", name: "Vietnam", emoji: "🇻🇳", region: "Asia" },
  { code: "WF", name: "Wallis and Futuna", emoji: "🇼🇫", region: "Oceania" },
  { code: "EH", name: "Western Sahara", emoji: "🇪🇭", region: "Africa" },
  { code: "YE", name: "Yemen", emoji: "🇾🇪", region: "Asia" },
  { code: "ZM", name: "Zambia", emoji: "🇿🇲", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", emoji: "🇿🇼", region: "Africa" },
];

export const COUNTRY_CODES: readonly string[] = COUNTRIES.map(
  (country) => country.code,
);

const byCode = new Map(COUNTRIES.map((country) => [country.code, country]));

export function getCountry(code: string | null | undefined) {
  if (!code) return null;
  return byCode.get(code.trim().toUpperCase()) ?? null;
}

export function isCountryCode(code: string | null | undefined) {
  return getCountry(code) !== null;
}

/**
 * Region stays available as a grouping dimension — African student
 * communities remain a real part of Kondo, they are simply no longer the
 * definition of who Kondo is for.
 */
export function countriesInRegion(region: CountryRegion) {
  return COUNTRIES.filter((country) => country.region === region);
}

/** Options shaped for `SearchableSelect`, searchable by name and by code. */
export function countrySelectOptions() {
  return COUNTRIES.map((country) => ({
    id: country.code,
    name: `${country.emoji} ${country.name}`,
    secondary: country.region,
  }));
}
