export type SupportedCurrency = {
  code: string;
  name: string;
  symbol: string;
};

export const SUPPORTED_CURRENCIES: SupportedCurrency[] = [
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "DZD", name: "Algerian Dinar", symbol: "DA" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "L" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "DH" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS£" },
  { code: "SDG", name: "Sudanese Pound", symbol: "SDG" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
];

export const SUPPORTED_CURRENCY_CODES = new Set(
  SUPPORTED_CURRENCIES.map((currency) => currency.code),
);
