export type SupportedCurrency = {
  code: string;
  name: string;
  symbol: string;
};

/**
 * Every circulating ISO 4217 currency.
 *
 * Kondo prices most things in CNY, but the people using it come from
 * everywhere, and a currency picker is one of the places a product quietly
 * tells you who it was built for. The four a student in China reaches for
 * first lead the list; the rest follow alphabetically.
 *
 * Regenerate with `npm run reference:currencies`.
 */
export const SUPPORTED_CURRENCIES: SupportedCurrency[] = [
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "AFN", name: "Afghan Afghani", symbol: "AFN" },
  { code: "ALL", name: "Albanian Lek", symbol: "ALL" },
  { code: "DZD", name: "Algerian Dinar", symbol: "DA" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "ARS", name: "Argentine Peso", symbol: "ARS" },
  { code: "AMD", name: "Armenian Dram", symbol: "AMD" },
  { code: "AWG", name: "Aruban Florin", symbol: "AWG" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "AZN" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "BSD" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BHD" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "BBD" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "BYN" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZD" },
  { code: "BMD", name: "Bermudan Dollar", symbol: "BMD" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "BTN" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "BOB" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "BAM" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "BND", name: "Brunei Dollar", symbol: "BND" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "BGN" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { code: "XCG", name: "Caribbean guilder", symbol: "Cg." },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "KYD" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XPF", name: "CFP Franc", symbol: "CFPF" },
  { code: "CLP", name: "Chilean Peso", symbol: "CLP" },
  { code: "COP", name: "Colombian Peso", symbol: "COP" },
  { code: "KMF", name: "Comorian Franc", symbol: "KMF" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "CRC" },
  { code: "HRK", name: "Croatian Kuna", symbol: "HRK" },
  { code: "CUC", name: "Cuban Convertible Peso", symbol: "CUC" },
  { code: "CUP", name: "Cuban Peso", symbol: "CUP" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DOP", name: "Dominican Peso", symbol: "DOP" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "L" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "FKP" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJD" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GEL", name: "Georgian Lari", symbol: "GEL" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "GIP" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "GTQ" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "GYD", name: "Guyanaese Dollar", symbol: "GYD" },
  { code: "HTG", name: "Haitian Gourde", symbol: "HTG" },
  { code: "HNL", name: "Honduran Lempira", symbol: "HNL" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "ISK", name: "Icelandic Króna", symbol: "ISK" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "IRR", name: "Iranian Rial", symbol: "IRR" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "IQD" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "JMD" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JOD" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KWD" },
  { code: "KGS", name: "Kyrgyz Som", symbol: "KGS" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭" },
  { code: "LBP", name: "Lebanese Pound", symbol: "LBP" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP" },
  { code: "MKD", name: "Macedonian Denar", symbol: "MKD" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "MVR" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
  { code: "MDL", name: "Moldovan Leu", symbol: "MDL" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "DH" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "MMK" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "रू" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ANG" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "NIO" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "KPW", name: "North Korean Won", symbol: "KPW" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "OMR", name: "Omani Rial", symbol: "OMR" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "PAB" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "PGK" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "PYG" },
  { code: "PEN", name: "Peruvian Sol", symbol: "PEN" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "QAR", name: "Qatari Riyal", symbol: "QAR" },
  { code: "RON", name: "Romanian Leu", symbol: "RON" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "SVC", name: "Salvadoran Colón", symbol: "SVC" },
  { code: "WST", name: "Samoan Tala", symbol: "WST" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "SAR", name: "Saudi Riyal", symbol: "SAR" },
  { code: "RSD", name: "Serbian Dinar", symbol: "RSD" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SLL", name: "Sierra Leonean Leone (1964—2022)", symbol: "SLL" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SBD" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS£" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "SHP", name: "St. Helena Pound", symbol: "SHP" },
  { code: "SDG", name: "Sudanese Pound", symbol: "SDG" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "SRD" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "SYP", name: "Syrian Pound", symbol: "SYP" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "TJS" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "TOP" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TTD" },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "TMT" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "UYU" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "UZS" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VUV" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "VES" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "YER", name: "Yemeni Rial", symbol: "YER" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$" },
  { code: "ZWG", name: "Zimbabwean Gold", symbol: "ZWG" },
];

export const SUPPORTED_CURRENCY_CODES = new Set(
  SUPPORTED_CURRENCIES.map((currency) => currency.code),
);
