ALTER TYPE "AnalyticsEventName" ADD VALUE 'USER_REGISTERED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'USER_LOGGED_IN';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'COMMUNITY_CREATED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'LISTING_CREATED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'MESSAGE_SENT';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'STUDENT_HUB_VIEWED';
ALTER TYPE "AnalyticsEventName" ADD VALUE 'EXPLORE_CITY_VIEWED';
