-- Part 5, phase 1: commit additive values on existing PostgreSQL enums before
-- the Opportunity schema, media policies and notification templates use them.
-- PostgreSQL cannot use a newly added enum value in the transaction that adds
-- it, so this phase stays separate from the domain migration.

ALTER TYPE "NotificationType"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY';

ALTER TYPE "ReportEvidenceKind"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_SNAPSHOT';

ALTER TYPE "MediaPurpose"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_COVER_IMAGE';
ALTER TYPE "MediaPurpose"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_DOCUMENT';

ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITIES_HOME_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_CATEGORY_OPENED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_SEARCH_STARTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_FILTER_APPLIED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_SAVED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_UNSAVED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_SHARED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_ELIGIBILITY_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_STARTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_DRAFT_SAVED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_DOCUMENT_SELECTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_SUBMITTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_STATUS_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_APPLICATION_WITHDRAWN';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_EXTERNAL_APPLICATION_OPENED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ORGANIZATION_OPPORTUNITY_CREATED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ORGANIZATION_OPPORTUNITY_SUBMITTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ORGANIZATION_OPPORTUNITY_PUBLISHED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ORGANIZATION_APPLICATIONS_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ORGANIZATION_APPLICATION_STATUS_CHANGED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'OPPORTUNITY_REPORT_SUBMITTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'STUDENT_HUB_OPPORTUNITY_OPENED';
