-- Part 4, phase 1: commit additive values on existing PostgreSQL enums before
-- the Housing schema and notification templates use them.

ALTER TYPE "NotificationType"
  ADD VALUE IF NOT EXISTS 'HOUSING';

ALTER TYPE "ReportEvidenceKind"
  ADD VALUE IF NOT EXISTS 'HOUSING_CONTENT_SNAPSHOT';

ALTER TYPE "MediaPurpose"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_IMAGE';
ALTER TYPE "MediaPurpose"
  ADD VALUE IF NOT EXISTS 'HOUSING_FLOOR_PLAN';
ALTER TYPE "MediaPurpose"
  ADD VALUE IF NOT EXISTS 'HOUSING_PROOF_DOCUMENT';

ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_HOME_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_SEARCH_STARTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_FILTER_APPLIED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_MAP_OPENED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_SAVED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_CONTACT_OPENED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_INQUIRY_SENT';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_CREATED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_SUBMITTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_LISTING_PUBLISHED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_REQUEST_CREATED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_REQUEST_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ROOMMATE_PROFILE_CREATED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ROOMMATE_DISCOVERY_VIEWED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ROOMMATE_INTEREST_SENT';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'ROOMMATE_INTEREST_ACCEPTED';
ALTER TYPE "AnalyticsEventName"
  ADD VALUE IF NOT EXISTS 'HOUSING_REPORT_SUBMITTED';
