ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMUNITY_ACTIVITY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEET_ACTIVITY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACADEMIC';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RECOMMENDATION';

ALTER TABLE "UserPreference"
ADD COLUMN "notificationCommunity" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notificationMeet" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notificationAcademic" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notificationRecommendations" BOOLEAN NOT NULL DEFAULT true;
